# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: kkagent

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/WebApp.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build Web App
  inputs:
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    testRunTitle: 'Run Unit Tests'

- task: DotNetCoreCLI@2
  displayName: Create Web App Package (.zip)
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
